### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by dcode** [peasead/msg_viewer#1]
Is there source available for this? While it's great to use some other app to avoid potentially malicious messages, why should I trust some random binary? Maybe the source is available somewhere else?

**Comment by peasead** [comment]
I had the same concerns, but it appears to have a good reputation, doesn't look like some random script, and all the public scanners said it wasn't bad. Your mileage may vary.

If you're super curious, https://www.hex-rays.com/products/ida/index.shtml

http://sourceforge.net/projects/msgviewer/

**Comment by dcode** [comment]
Ah...you should provide the Source forge link in the readme...then I don't have to take you at your word ;-)

SVN Trunk: http://sourceforge.net/p/msgviewer/code/HEAD/tree/Main/trunk/

**Comment by peasead** [comment]
done.
